    <nav>
        <div id="box1">
        <div class="NAV-container">
            
            <a href="index.php" class="home-link">
                <div class="home-button">
                    <img src="images/logo.png" alt="home">
                </div>
            </a>
            
        <select class="nav-select">
            <option value="" disabled selected>Select an option</option>
            <option value="home">Home</option>
            <option value="pets">Pets</option>
            <option value="addpet">Add Pet</option>
            <option value="gallery">Gallery</option>
        </select>

            
            <script src="js_folder/main.js"></script>
        </div>
        <div class="search-container">
            <input type="text" placeholder="Search" class="search-input">
            <button class="search-button">
                <span class="material-symbols-outlined">search</span> 
            </button>
        </div>        
    </div>
</nav>